name: Update TV Box Content

on:
  schedule:
    - cron: '0 2 * * *'  # 每天北京时间的10点运行
      timezone: Asia/Shanghai  # 设置时区为上海（北京）时间
  workflow_dispatch:  # 手动触发

jobs:
  update_tv_box:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: python .github/workflows/update_tvbox.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tvbox.txt
        git commit -m "Update TV Box content" --allow-empty
        git push
